stages:
    - test
    - inspect
    - deploydocker

test:
    stage: test
    script:
        - dotnet test ManagementService.sln

inspect:
  stage: inspect
  script:
    - dotnet new tool-manifest
    - dotnet tool install JetBrains.ReSharper.GlobalTools --version=2023.1.1
    - dotnet jb inspectcode ManagementService.sln -o=/ManagementReport
    - dotnet tool restore

deploydocker: 
    stage: deploydocker
    script:
        - ./build_services.bat
        
before_script:
  - cd ManagementService
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

sast:
  tags:
    - dock-runner
  script:
    - wget https://dot.net/v1/dotnet-install.sh
    - bash ./dotnet-install.sh -c 7.0
    - dotnet new xunit
