stages:
    - test
    - deploytoaks
test:
    stage: test
    script:
        - echo "integrated test"
deploystoaks:
    stage: deploytoaks
    script:
        - cd k8s
        - kubectl apply -f keycloak-sercret.yaml
        - kubectl apply -f keycloak-config.yaml
        - kubectl apply -f postgres-config.yaml
        - kubectl apply -f postgres-secret.yaml
        - kubectl apply -f postgres.yaml
        - kubectl apply -f fron_end.yaml
        - kubectl apply -f management.yaml
        - kubectl apply -f game.yaml
