stages:
    - test
    - inspect
    - deploydocker
include: 
    - tempalte: Security/Dependency-Scanning.gitlab-ci.yml
    - tempalte: Security/SAST.gitlab-ci.yml
test:
    stage: test
    script:
        - dotnet test ManagementService/ManagementService.sln

inspect:
  stage: inspect
  script:
    - dotnet new tool-manifest
    - dotnet tool install JetBrains.ReSharper.GlobalTools --version=2023.1.1
    - dotnet jb inspectcode ManagementService/ManagementService.sln -o=/ManagementReport
    - dotnet tool restore

deploydocker: 
    stage: deploydocker
    script:
        - cd ManagementService
        - ./build_services.bat
