stages:
    - test
    - inspect
    - deploydocker

before_script:
  - cd ManagementService

test:
    stage: test
    script:
        - dotnet test ManagementService.sln

inspect:
  stage: inspect
  script:
    - dotnet new tool-manifest
    - dotnet tool install JetBrains.ReSharper.GlobalTools --version=2023.1.1
    - dotnet jb inspectcode ManagementService.sln -o=/ManagementReport
    - dotnet tool restore

deploydocker: 
    stage: deploydocker
    script:
        - ./build_services.bat
        
include:
   local: 'analize.gitlab-ci.yml'
