stages:
    - test
    - inspect
    - deploydocker
test:
    stage: test
    script:
        - Write-Host "Hello, World!"

inspect:
  stage: inspect
  script:
    - dotnet new tool-manifest
    - dotnet tool install JetBrains.ReSharper.GlobalTools --version=2023.1.1
    - dotnet jb inspectcode ManagementService/ManagementService.sln -o=/ManagementReport
    - dotnet tool restore

deploydocker: 
    stage: deploydocker
    script:
        - cd ManagementService
        - ./build_services.bat
