version: "3.8"

services:
  engine-management:
    image: engine_managment
    ports:
      - "5000:5000"
    volumes:
      - .info/:/app/info/
      - .engines/:/app/engines/
  management:
    image: management
    ports:
      - "5001:5001"
    volumes:
      - .info/:/app/info/
      - .engines/:/app/engines/
  load-balancer:
    image: nginx:latest
    ports:
      - "5002:5002"
    volumes:
      - .nginx/:/etc/nginx/
volumes:
  engines:
  info: