version: "3.8"

services:
  engine-management:
    image: engine_managment
    ports:
      - "5000:5000"
    volumes:
      - .info/:/app/info/
      - .engines/:/app/engines/
  management:
    image: management
    ports:
      - "5001:5001"
    volumes:
      - .info/:/app/info/
      - .engines/:/app/engines/
    networks: 
      - mynetwork
  load-balancer:
    image: nginx:latest
    ports:
      - "5002:5002"
    volumes:
      - .nginx/:/etc/nginx/
  front-end:
    image: front_end
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks: 
      - mynetwork
    ports:
      - 5432:5432
  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABSE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password            
    ports:
      - 5003:8080
    networks: 
      - mynetwork
    depends_on:
      - postgres
volumes:
  engines:
  info:
  postgres_data:
networks:
  mynetwork:
     name: mynetwork
