apiVersion: v1
kind: PersistentVolume
metadata:
  name: configuration-volume
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: configuration-volume
  hostPath:
    path: /data/engines/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configuration-volume
  namespace: chess
  labels:
    app: configuration-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: configuration-volume

