apiVersion: v1
kind: PersistentVolume
metadata:
  name: reverseproxy-volume
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: reverseproxy-volume
  hostPath:
    path: /etc/nginx/conf.d
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reverseproxy-volume
  namespace: chess
  labels:
    app: reverseproxy-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: reverseproxy-volume
